-- FounderSaathi production RAG hardening
-- Run once in Supabase SQL Editor.

-- 1) Persistent embedding cache.
create table if not exists public.rag_embedding_cache (
    cache_key text primary key,
    task_type text not null check (
        task_type in ('RETRIEVAL_QUERY', 'RETRIEVAL_DOCUMENT')
    ),
    model text not null,
    dimensions integer not null,
    embedding vector(768) not null,
    created_at timestamptz not null default now(),
    last_used_at timestamptz not null default now(),
    hit_count integer not null default 0
);

create index if not exists rag_embedding_cache_last_used_idx
    on public.rag_embedding_cache(last_used_at desc);

alter table public.rag_embedding_cache enable row level security;

-- No client policies: only the server service-role client can access the cache.

-- 2) RAG search observability.
create table if not exists public.rag_search_logs (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete set null,
    query_hash text not null,
    result_count integer not null default 0,
    latency_ms integer not null default 0,
    threshold real not null,
    result_limit integer not null,
    status text not null check (
        status in ('success', 'error', 'skipped_non_rag')
    ),
    error_message text,
    created_at timestamptz not null default now()
);

create index if not exists rag_search_logs_created_at_idx
    on public.rag_search_logs(created_at desc);

create index if not exists rag_search_logs_user_created_idx
    on public.rag_search_logs(user_id, created_at desc);

alter table public.rag_search_logs enable row level security;

-- No client policies: logs are server-side only.

-- 3) Tighten RAG table writes.
-- Search still needs read access. Ingestion now uses the service-role client.
alter table public.rag_documents enable row level security;
alter table public.rag_chunks enable row level security;

drop policy if exists "Users can insert RAG documents"
    on public.rag_documents;
drop policy if exists "Users can delete RAG documents"
    on public.rag_documents;
drop policy if exists "Users can insert RAG chunks"
    on public.rag_chunks;
drop policy if exists "Users can delete RAG chunks"
    on public.rag_chunks;

drop policy if exists "Authenticated users can read RAG documents"
    on public.rag_documents;
drop policy if exists "Authenticated users can read RAG chunks"
    on public.rag_chunks;

create policy "Authenticated users can read RAG documents"
    on public.rag_documents
    for select
    to authenticated
    using (true);

create policy "Authenticated users can read RAG chunks"
    on public.rag_chunks
    for select
    to authenticated
    using (true);

-- 4) Useful diagnostic query for the existing RPCs.
-- Run separately if you want to inspect their exact definitions.
-- select p.oid::regprocedure as routine,
--        pg_get_functiondef(p.oid) as definition
-- from pg_proc p
-- join pg_namespace n on n.oid = p.pronamespace
-- where n.nspname = 'public'
--   and p.proname in ('match_rag_chunks', 'hybrid_search_rag_chunks')
-- order by 1;
